import json, urllib.request

SUPABASE_URL = "https://jcgvkyizoimwbolhfpta.supabase.co"
ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZ3ZreWl6b2ltd2JvbGhmcHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDMwMjQsImV4cCI6MjA4NTg3OTAyNH0.a8gjkPoUHQ1kgROa2Lqaq3252opqg5CPMm6vR3t1NOk"

emails = [
("restaurants","restaurants",1,1,"People Google your restaurant before they walk in. What do they find?","Book a Free Restaurant Strategy Call","https://newurbaninfluence.com/contact","Quick question - when someone in Detroit searches for what your restaurant serves, does your name come up? Not just on Google Maps. On voice search. On AI overviews. On the map pack for every neighborhood within 10 miles.\n\nMost restaurants in this city are banking on regulars and word of mouth - which works until it doesn't. One slow month, one new competitor, one bad review and the whole thing shifts.\n\nWe've helped Detroit restaurants build visibility that doesn't depend on any single channel. Your menu, your story, your reviews, and your location - showing up everywhere, all the time, without you lifting a finger.\n\nI'd love to show you exactly what we'd do for your spot - no pitch, no obligation. Just 15 minutes.\n\nFaren Young\nNew Urban Influence | (248) 487-8747"),
("restaurants","restaurants",2,3,"How Detroit restaurants go from hard to find to fully booked","Get My Free Visibility Audit","https://newurbaninfluence.com/contact","You built something real. The food is there. The atmosphere is there. The problem is that too many people don't know you exist yet.\n\nWe've worked with Detroit-area restaurants on exactly this - building their digital presence so discovery happens automatically, not just through regulars and Yelp luck.\n\nThe shift: A consistent Google Maps presence across multiple zip codes. A website that loads fast on mobile. Social media content that gets shared - not just liked and scrolled past.\n\nYou're not competing with every restaurant in Detroit. You're competing with the ones showing up when your ideal customer opens their phone right now.\n\nWe'll audit your current visibility for free and show you exactly where the gaps are.\n\nFaren"),
("restaurants","restaurants",3,7,"The myth: We get enough customers from social media","See What a Digital HQ Looks Like","https://newurbaninfluence.com/services/business-website-detroit","Here's something we hear from restaurant owners all the time: We post on Instagram every day, we're good.\n\nInstagram is a retention tool - it keeps your regulars engaged. But it's almost never how new customers find you for the first time. That happens on Google. On Maps. On AI answers to best [food type] near me.\n\nWhen someone who has never heard of you is hungry tonight, they're not scrolling Instagram. They're searching. The question is whether you're the answer they find.\n\nWe build Digital HQs - full business systems that make sure you're the answer. Your site, your maps presence, your review management, and your follow-up system all working together.\n\nFaren"),
("restaurants","restaurants",4,10,"I can't afford an agency right now - let me address that directly","See Financing Options","https://newurbaninfluence.com/services/business-website-detroit","When a restaurant owner tells me they can't afford marketing, what I'm hearing is: spending money on food costs, staff, rent - and marketing feels like a luxury. That's a real tension.\n\nHere's what I'd ask you to consider: the restaurants in Detroit that are full on Tuesday nights aren't necessarily better than you. They're more findable. And findability is a one-time investment that pays you back every single month.\n\nOur packages start at $2,500 for a full brand build and $3,500 for a complete Digital HQ. We offer Afterpay and Klarna so you can start now and pay over time at 0% interest. Starting from $89/mo.\n\nWhat would it mean for your restaurant to have 20 more covers a week from new customers who found you online?\n\nFaren"),
("restaurants","restaurants",5,14,"Last one from me - then I'll leave you alone","Book That 15-Minute Call","https://newurbaninfluence.com/contact","I've sent you a few emails over the past two weeks. If they haven't landed, that's okay - the timing wasn't right and I get it.\n\nBut if any of this has been rattling around in the back of your mind - the Google visibility, the website that doesn't quite work, the customers who find your competitor instead - the conversation is still open.\n\nWe work with Detroit restaurants specifically because this city deserves businesses that thrive. We're not a national agency that treats every client the same. We're Detroit, and we build for Detroit.\n\nOne 15-minute call is all it takes. I'll pull your current online presence, show you what's working and what isn't, and give you a real plan - whether you work with us or not.\n\nFaren"),
("nightlife","bars_nightlife",1,1,"Facebook keeps blocking your ads. Here's what actually works for nightlife.","Book a Nightlife Strategy Call","https://newurbaninfluence.com/contact","If you run a bar or club, you already know the headache: you try to promote an event, Facebook flags it. You boost a post, it gets half the reach. You pay for ads and they get rejected.\n\nThis is policy. Facebook and Google have content restrictions that disproportionately hit nightlife businesses. Most venues give up and just rely on Instagram and word of mouth.\n\nThere's a different approach. Geofencing runs completely outside Facebook and Google's ad platforms, so none of those restrictions apply.\n\nWe set up a virtual boundary around any location: a stadium on game night, your competitor's parking lot, a neighborhood. Everyone whose phone enters that zone sees your ad - and keeps seeing it for up to 30 days after they leave.\n\nInterested in how it would work for your venue? Let's talk.\n\nFaren"),
("nightlife","bars_nightlife",2,3,"Your flyers are reaching the same 300 people every time","Show Me the Blueprint","https://newurbaninfluence.com/services/business-website-detroit","Flyers work. They always have. But at some point you hit a ceiling - you're reaching the same loyal crowd over and over, and the growth stops.\n\nWe call geofencing the digital flyer. Instead of paying someone to stand outside your competitor and hand out cards, we plant your brand on every phone in their parking lot. Then those people see you again for the next month.\n\nThink about the Stadium corridor on game nights. Eastern Market on weekends. A competing venue on a Saturday. That's your audience - people already in party mode, already looking for somewhere to go.\n\nWe also build the system behind it: the Digital HQ that captures those leads, the SMS list that keeps them coming back, the content that makes your bar look packed even on a slow Tuesday.\n\nFaren"),
("nightlife","bars_nightlife",3,7,"What building an audience actually means for a bar or club","Build My Venue's Audience System","https://newurbaninfluence.com/services/digital-staff-detroit","Most nightlife venues think about filling the room for the next event. We think about building an audience that fills the room for every event.\n\nThere's a difference between a crowd and a list. A crowd shows up when you hustle. A list shows up because they want to. Every text you send, every push notification, every photo from last weekend - it all feeds the same system.\n\nThe Digital Promoter is our tool for this: SMS campaigns, push notifications, and retargeting ads running on your behalf 24/7. New event? It goes to your list. Big night coming? Retargeting fires automatically.\n\nThis is what serious venues do. The cover charge pays for the night. The list pays for the year.\n\nFaren"),
("nightlife","bars_nightlife",4,10,"A specific strategy for your venue - no generic pitch","Let's Talk Strategy","https://newurbaninfluence.com/contact","I want to be direct with you because I think you deserve more than a template.\n\nFor a bar or club in Detroit, the moves that actually move the needle are: (1) geofencing competitor locations to capture intent at the moment it happens, (2) SMS and push notifications to your own list, and (3) content that makes your venue look like the place to be, posted consistently.\n\nThat's the Digital Street Team package. The Content Crew handles your social. The Digital Promoter handles your owned channels. The Block Captain handles geofencing.\n\nYou don't need all three on day one. But knowing where to start is the strategy.\n\n15 minutes. No obligation.\n\nFaren"),
("nightlife","bars_nightlife",5,14,"Closing the loop - one more thing before I go quiet","Start That Conversation","https://newurbaninfluence.com/contact","I've reached out a few times because I genuinely believe the right digital strategy changes the trajectory of a venue. Packed Fridays are great. Consistent Thursdays, Saturdays, and holiday weekends are a business.\n\nIf any of this landed - the geofencing angle, the SMS audience, the content operation - the door is still open.\n\nAnd if the timing wasn't right, save this email. The next time you're staring at a slow night wondering how to bring people in, this is the conversation to have.\n\nDetroit nightlife is resilient. The venues that are winning right now have systems, not just hustle. We build the systems.\n\nFaren"),
("hvac","hvac",1,1,"When someone in Southfield searches HVAC near me - are you coming up?","Pull My Google Footprint","https://newurbaninfluence.com/contact","The big HVAC players own the map in Metro Detroit. When homeowners search for AC repair, furnace installation, or duct cleaning, the same 3-4 companies keep showing up.\n\nIt's not because they're better. It's because they've worked the map. Google Business Profiles optimized for every zip code in their territory. Reviews in Southfield, Sterling Heights, Dearborn, and Livonia - even if their office is in Troy.\n\nWe call this geo-gridding. It's the process of systematically expanding your Google Maps footprint one zip code at a time, until you own your entire territory.\n\nThe HVAC companies we've helped go from showing up in one city to showing up in every neighborhood they service - without running a single paid ad.\n\nWant to see what your territory looks like right now?\n\nFaren"),
("hvac","hvac",2,3,"The HVAC companies winning in Detroit right now are doing this","See the HVAC Digital HQ","https://newurbaninfluence.com/services/business-website-detroit","The season comes, the phone rings. Then the season ends, and the phone gets quiet. If your HVAC business runs like this, you're leaving a lot of jobs on the table.\n\nThe companies that stay busy year-round have built a lead system that runs even when the phone doesn't ring. Their website converts. Their Google presence covers the whole territory. Their follow-up is automated.\n\nWe build this for HVAC companies. It's called a Digital HQ - not just a website, but the full infrastructure that keeps your business open 24/7. Leads come in from the map, from search. Captured automatically. Estimates requested. Follow-ups sent.\n\nYou focus on the service calls. The system handles the pipeline.\n\nFaren"),
("hvac","hvac",3,7,"Why your Google ads spend keeps going up and your leads stay flat","Talk Through the Strategy","https://newurbaninfluence.com/contact","A lot of HVAC companies come to us after the same frustration: paying $2,000-$5,000 a month in Google Ads, and the cost-per-lead keeps rising while quality keeps dropping.\n\nHere's what's happening: you're renting visibility. The moment you stop paying, you disappear. And every year, more HVAC companies enter the ad auction and drive your cost up.\n\nThe alternative is owned visibility - building your presence so strong in organic results and maps that the phone calls come without ongoing ad spend. It takes longer to build. But once it's there, it's yours.\n\nWe do both: get you visible immediately through strategic local SEO and geo-gridding, and build the long-term asset so you're not dependent on ads forever.\n\nFaren"),
("hvac","hvac",4,10,"Storm season is coming. Is your HVAC business positioned to capture the surge?","Build My Lead Capture System","https://newurbaninfluence.com/services/digital-staff-detroit","Every HVAC operator knows the pattern: weather event hits, the phones go crazy for a week, then it's back to slow. The companies that turn those surges into sustained growth have a system for capturing and following up with every single lead during the peak.\n\nMost HVAC companies are too busy during the surge to follow up properly. By the time things slow down, those leads have moved on to whoever called them back first.\n\nThe Digital Staff system we build handles this automatically. Every lead that comes in gets an immediate follow-up. Estimate request sent. Appointment offered. No lead falls through the cracks.\n\nThis just needs to be set up correctly once. We do that.\n\nFaren"),
("hvac","hvac",5,14,"Final note - the map territory conversation","Book My Territory Strategy Call","https://newurbaninfluence.com/contact","I've reached out a few times because territory visibility is genuinely one of the highest-ROI moves an HVAC company can make in this market.\n\nThe contractor who shows up in every zip code in your service territory - Southfield, Royal Oak, Dearborn, Livonia, Sterling Heights - wins the job before the estimate call even happens. That's the power of owning the map.\n\nIf you haven't booked a call yet, I understand. Timing is everything in this business. But save this email.\n\nWhen you're ready to talk about building the kind of digital presence that makes you the obvious choice in every neighborhood you service, this is the conversation.\n\nFaren"),
("roofing","roofing",1,1,"Homeowners spending $15K on a roof are Googling you right now. What do they find?","Pull My Online Presence Report","https://newurbaninfluence.com/contact","A homeowner is about to write one of the biggest checks they'll write all year. Before they call anyone, they Google. They check reviews. They visit websites. They look at photos of past jobs.\n\nWhat they find determines who gets the estimate call - and most of the time, who gets the job.\n\nHere's what a lot of roofing companies in Metro Detroit are missing: a website that actually builds trust. Professional photos of past work. Reviews in multiple zip codes. A presence that shows up when homeowners search roof replacement near me in Southfield, Livonia, Royal Oak, Dearborn.\n\nWe build all of this. A complete Digital HQ that positions your roofing company as the obvious, credible choice - before the estimate call even happens.\n\nFaren"),
("roofing","roofing",2,3,"After the storm: are you the first roofer homeowners see?","Build My Storm Response System","https://newurbaninfluence.com/services/business-website-detroit","Storm rolls through Metro Detroit. Hail damage. Shingle blow-offs. The phones ring for a week - for some roofers. For others, the storm comes and goes and they barely noticed the uptick.\n\nThe difference is almost always online presence. Homeowners go to Google immediately after storm damage. The roofing companies that show up in those results get the surge.\n\nGeofencing is our storm strategy: we set up boundaries around the hardest-hit neighborhoods in real time, so your ads appear on every phone in those areas within hours of a weather event.\n\nCombine that with a Digital HQ that converts visitors into estimate requests, and you've built a storm response machine that runs while you're already on the job.\n\nFaren"),
("roofing","roofing",3,7,"Why we get all our work from referrals is a vulnerability","Turn My Reputation Into Digital Reach","https://newurbaninfluence.com/services/business-website-detroit","Referrals are the best leads you'll ever get. If your roofing business runs mostly on them, that's a sign you do great work and your customers trust you.\n\nBut referrals are unpredictable. They surge when you've just finished a job and the neighbor saw the crew. They dry up in winter, after a slow stretch, or when your existing customers don't know anyone needing a roof right now.\n\nThe roofing companies that grow past a certain ceiling have turned their referral reputation into a digital one. Their reviews, their photos, their website, their Google presence - all of it says the same thing the neighbor would say. Except it says it to 10,000 people searching.\n\nWe do this transition. If you've got the reputation and the craftsmanship, we build the digital infrastructure.\n\nFaren"),
("roofing","roofing",4,10,"The press feature that closes roofing estimates before you pick up the phone","Get My Roofing Feature","https://newurbaninfluence.com/services/press-feature-detroit","There's a specific tool we use for high-ticket service contractors that very few people know about: a press feature.\n\nWhen a homeowner is comparing three roofing companies and one of them has been featured in a publication - a professional editorial profile with their story, their work, and their credibility - the psychology shifts. It's not you saying you're the best. It's someone else saying it.\n\nWe publish features in NUI Magazine. Professional editorial. Permanent URL. As featured in NUI Magazine badge for your website and estimates.\n\nFor a $15,000 roofing job, this is the difference between a homeowner who calls three people and a homeowner who already decided.\n\nThe Publicist package starts at $1,500. It's the easiest credibility upgrade in this business.\n\nFaren"),
("roofing","roofing",5,14,"Closing out - the roofing territory play","Book My 15-Minute Territory Call","https://newurbaninfluence.com/contact","Last note from me. If you've been opening these emails, you already know the problem we solve: visibility in your territory, trust signals that convert, and systems that capture leads automatically.\n\nThe roofing market in Metro Detroit is competitive but fragmented. Most contractors are still relying on yard signs, direct mail, and referrals. The ones building digital infrastructure right now will own their territory for the next five years.\n\nWe're seeing this play out in real time. Roofing companies that made the investment in their digital presence 18 months ago are now booked out. The ones that waited are playing catch-up.\n\nIf you're ready to have the real conversation, book the call. 15 minutes.\n\nFaren"),
("flooring","flooring",1,1,"Most flooring leads go to whoever follows up first. Is that you?","See the Lead Catcher System","https://newurbaninfluence.com/services/digital-staff-detroit","Flooring is a considered purchase. Homeowners research, get multiple quotes, take their time. And in that window between I'm interested and I've made a decision, the company that follows up fastest almost always wins the job.\n\nMost flooring companies are leaving this to chance. A lead comes in, someone follows up the next day, or maybe two days later. By then, two competitors have already sent quotes.\n\nWe fix this with automation. When someone submits an inquiry, they get a response within minutes. Not a template. A smart follow-up system that qualifies them, answers their questions, and books the estimate while you're on a job.\n\nThis is the Lead Catcher - one of the positions on our Digital Staff. It doesn't sleep, it doesn't forget, and it follows up on every single inquiry.\n\nFaren"),
("flooring","flooring",2,3,"Your showroom looks great. Does your website?","See My Digital HQ Options","https://newurbaninfluence.com/services/business-website-detroit","Most flooring companies spend serious money on their showroom - the samples, the displays, the in-person experience. And then their website looks like it was built in 2014 and hasn't been touched since.\n\nHere's the thing: your website is your showroom for the 85% of customers who look online before they ever step foot inside. If the photos are low quality, the navigation is confusing, or the site doesn't load right on mobile, those potential customers are clicking back to your competitor.\n\nWe build Digital HQs for flooring companies. A site that shows your work beautifully, loads fast on every device, has a clear process for getting a quote, and captures every visitor's information for follow-up.\n\nThe showroom closes the sale. The website gets them in the door.\n\nFaren"),
("flooring","flooring",3,7,"The renovation wave in Metro Detroit - are you capturing it?","Capture My Territory","https://newurbaninfluence.com/contact","Detroit's housing market has been moving. Older homes getting updated. Buyers coming in and renovating. The renovation wave is real - and flooring is almost always on the list.\n\nThe flooring companies positioned to capture this wave are the ones showing up when homeowners search. Not just for their brand name, but for terms like hardwood floor installation Livonia or LVP flooring contractor Southfield or tile installation near me.\n\nThis is territory coverage - making sure your business appears across every city and neighborhood in your service area, not just the zip code your showroom is in.\n\nWe build this systematically: your Google Business Profile optimized for every territory, your website content targeting the searches that matter.\n\nFaren"),
("flooring","flooring",4,10,"What Powered by NUI means for your flooring business","Build My Flooring Business System","https://newurbaninfluence.com/services/business-website-detroit","I want to be clear about what working with us actually looks like - because I think it's different from what most people expect from a marketing agency.\n\nWe don't run your social media and send you a monthly report. We build infrastructure. Your Digital HQ is a permanent asset - a website, a lead capture system, a Google presence, and a follow-up machine that works for years.\n\nWe also stay connected to what's working. Your account gets regular audits. If something isn't converting, we fix it. If a new search term is driving traffic, we optimize for it.\n\nFor flooring specifically, we focus on the things that actually drive estimates: local search visibility, a site that converts browsers into callers, and follow-up that captures every inquiry.\n\nFaren"),
("flooring","flooring",5,14,"Last note - I'll leave the door open","Start the Conversation When Ready","https://newurbaninfluence.com/contact","I've sent a few emails over the past couple weeks. If the timing isn't right, I completely understand - flooring is a business driven by seasons and project backlogs, and sometimes the last thing you need is one more thing to think about.\n\nBut if you've been thinking about any of this - the visibility, the follow-up system, the website - the conversation is still open whenever you're ready.\n\nWe work with home improvement contractors across Metro Detroit. We know the market, we know the buying patterns, and we know exactly what moves the needle for businesses like yours.\n\nWhen the time is right, book the call. We'll be here.\n\nFaren"),
("lawn_care","lawn_care",1,1,"How are you staying in front of last year's customers right now?","Build My Retention System","https://newurbaninfluence.com/services/digital-staff-detroit","Lawn care is one of the most relationship-driven businesses in Metro Detroit. You do great work, the yard looks good, and the customer is happy. Then winter comes, and six months go by.\n\nWhen spring rolls around, that customer has two options: remember your number, or type lawn care near me into Google. Some of them remember you. A lot of them don't - not because they didn't like your work, but because they haven't thought about grass since October.\n\nThe lawn care companies that retain almost all of their customers year over year have a follow-up system. A newsletter that hits before spring. A text message in March. A reminder email. They stay top of mind so the search doesn't even happen.\n\nWe build this. And we connect it to a Digital HQ that captures new customers online while your existing system handles retention.\n\nFaren"),
("lawn_care","lawn_care",2,3,"The neighborhood play: how to own your territory street by street","Own My Territory","https://newurbaninfluence.com/contact","The best lawn care marketing doesn't look like marketing. It looks like your truck in the neighborhood, your yard signs on the good-looking lawns, and your business name in every Google Maps result when someone searches within 5 miles.\n\nWe call this territory coverage. We systematically build your Google presence across every neighborhood, subdivision, and zip code in your service area - so when a homeowner searches lawn care Farmington Hills or grass cutting service Troy, you're the first name they see.\n\nThis is geo-gridding. It works by optimizing your Google Business Profile for each territory systematically, building reviews in each area, and making sure your service areas show up in local search.\n\nCombined with a simple, fast-loading website that makes it easy to get an estimate, this becomes a lead machine that runs year-round.\n\nFaren"),
("lawn_care","lawn_care",3,7,"Spring is still a few months away. Here's how to use that time.","Use Winter to Build","https://newurbaninfluence.com/services/business-website-detroit","Most lawn care companies go quiet in winter. No marketing, no follow-up, just waiting for spring. And then spring comes and they scramble - trying to re-book customers, fill the schedule, run ads.\n\nThe companies that start spring ahead are the ones that used winter to build. They sent the emails. They updated the website. They set up the Google presence. They built the follow-up system.\n\nBy the time the grass starts growing, their schedule is already 70% booked from retention campaigns. The remaining 30% fills from organic search because the website and maps presence are ready.\n\nIf you've been meaning to get this infrastructure in place, winter is the time. Not spring when you're too busy, not summer when you're slammed.\n\nFaren"),
("lawn_care","lawn_care",4,10,"The $497/mo move that keeps your lawn care business visible all year","See the Complete Lawn Care Package","https://newurbaninfluence.com/services/social-media-management-detroit","I want to talk about something specific: the Content Crew.\n\nFor lawn care companies, consistent social media content does something specific and valuable - it keeps you visible to your existing customer base between seasons. Before-and-after photos. Lawn tips. Seasonal reminders. It's the reason they think of you in March instead of searching for someone new.\n\nOur Posted Up tier is $497/mo. Three posts a week, one platform, brand-consistent content created for you. You don't write anything, you don't schedule anything, you don't even think about it.\n\nAdd that to your Digital HQ - which handles new customer discovery - and you've got a complete system. Starting from $89/mo with our financing options.\n\nFaren"),
("lawn_care","lawn_care",5,14,"Wrapping up - the invitation stays open","Book My Free Strategy Call","https://newurbaninfluence.com/contact","Last email from me. If you've read any of these, you know what we do: we build the digital infrastructure that makes lawn care companies more findable, more retainable, and more referable.\n\nIt's not complicated. But it has to be done right, and it has to be done consistently. That's what we handle.\n\nIf the timing is right - or right enough - book the call. 15 minutes. I'll look at your current online presence, tell you exactly where the gaps are, and give you a real plan. Whether you work with us or not, you'll leave with something useful.\n\nAnd if the timing isn't right yet - save this email. Spring is coming.\n\nFaren"),
]

success = fail = 0
for (seq, ind, pos, days, subj, cta, url, body) in emails:
    payload = json.dumps({
        "sequence_id": seq, "industry": ind, "position": pos,
        "delay_days": days, "subject": subj, "cta_text": cta, "cta_url": url,
        "body_text": body, "body_html": "", "trigger_event": "form_submit", "active": True
    }).encode()
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/drip_emails",
        data=payload,
        headers={
            "apikey": ANON_KEY,
            "Authorization": f"Bearer {ANON_KEY}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates"
        }
    )
    req.get_method = lambda: "POST"
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            status = r.status
            success += 1
            print(f"✅ {seq} #{pos}")
    except urllib.error.HTTPError as ex:
        body_err = ex.read().decode()
        fail += 1
        print(f"❌ {seq} #{pos}: {ex.code} {body_err[:100]}")
    except Exception as ex:
        fail += 1
        print(f"❌ {seq} #{pos}: {str(ex)[:80]}")

print(f"\nDONE: {success} inserted, {fail} failed of {len(emails)}")
